"""Export AI remediation plans as a ready-to-run bash script or Ansible playbook.

These are generated from the same `Remediation` objects the interactive `fix`
applies. The bash script reproduces the transactional safety net (backup +
validate-before-reload + rollback-on-failure); the Ansible playbook wraps the
commands with a backup step and a service handler. The playbook is emitted as
JSON (which is valid YAML) so we keep the project's stdlib-only footprint.
"""

from __future__ import annotations

import json
from typing import List

from .models import Finding


def _fix_findings(findings: List[Finding]) -> List[Finding]:
    return [f for f in findings if f.remediation and f.remediation.commands]


def to_bash_script(findings: List[Finding]) -> str:
    """Render a self-contained, idempotent-ish bash remediation script."""
    out: List[str] = [
        "#!/usr/bin/env bash",
        "# Generated by vulnscan-ai. Review before running. Run as root.",
        "set -euo pipefail",
        "",
        'TS="$(date +%Y%m%d-%H%M%S)"',
        'BACKUP_ROOT="/var/backups/vulnscan-ai/$TS"',
        "backup() { for f in \"$@\"; do [ -f \"$f\" ] && install -D \"$f\" "
        "\"$BACKUP_ROOT$f\"; done; }",
        "restore() { for f in \"$@\"; do [ -f \"$BACKUP_ROOT$f\" ] && "
        "cp -a \"$BACKUP_ROOT$f\" \"$f\"; done; }",
        "",
    ]
    for f in _fix_findings(findings):
        rem = f.remediation
        assert rem is not None
        out.append(f"# ===== {f.title} =====")
        if rem.summary:
            out.append(f"# {rem.summary}")
        out.append(f"# risk={rem.risk} confidence={rem.confidence:.0%}")
        transactional = bool(rem.backup_paths or rem.service or rem.validate_cmd)
        if transactional:
            paths = " ".join(rem.backup_paths)
            svc = rem.service or ""
            mode = rem.restart_mode if rem.restart_mode in ("reload", "restart") else ""
            reload_cmd = f"systemctl {mode} {svc}" if (svc and mode) else "true"
            out.append("(")
            out.append("  set -e")
            if paths:
                out.append(f"  backup {paths}")
            trap_restore = f"restore {paths}; " if paths else ""
            trap_reload = f"{reload_cmd} || true; " if (svc and mode) else ""
            out.append(f"  trap 'echo \"FAILED — rolling back\"; {trap_restore}"
                       f"{trap_reload}exit 1' ERR")
            for c in rem.commands:
                out.append(f"  {c}")
            if rem.validate_cmd:
                out.append(f"  {rem.validate_cmd}   # validate before reload")
            if svc and mode:
                out.append(f"  {reload_cmd}")
            out.append(")")
        else:
            for c in rem.commands:
                out.append(c)
        out.append("")
    return "\n".join(out) + "\n"


def to_ansible_playbook(findings: List[Finding]) -> str:
    """Render an Ansible playbook (as JSON, which is valid YAML)."""
    tasks: List[dict] = []
    handlers: List[dict] = []
    seen_services = set()

    for f in _fix_findings(findings):
        rem = f.remediation
        assert rem is not None
        title = f.title or rem.summary or "remediation"
        notify = []
        if rem.service and rem.restart_mode in ("reload", "restart"):
            hname = f"{rem.restart_mode} {rem.service}"
            notify = [hname]
            if hname not in seen_services:
                seen_services.add(hname)
                handlers.append({
                    "name": hname,
                    "ansible.builtin.systemd": {
                        "name": rem.service, "state": f"{rem.restart_mode}ed",
                    },
                })
        for path in rem.backup_paths:
            tasks.append({
                "name": f"[{title}] backup {path}",
                "ansible.builtin.copy": {
                    "src": path, "dest": path, "remote_src": True, "backup": True,
                },
            })
        for i, cmd in enumerate(rem.commands, 1):
            task = {
                "name": f"[{title}] step {i}",
                "ansible.builtin.shell": cmd,
            }
            if notify:
                task["notify"] = notify
            tasks.append(task)
        if rem.validate_cmd:
            tasks.append({
                "name": f"[{title}] validate config",
                "ansible.builtin.command": rem.validate_cmd,
                "changed_when": False,
            })

    play = {
        "name": "vulnscan-ai generated remediation",
        "hosts": "all",
        "become": True,
        "tasks": tasks,
        "handlers": handlers,
    }
    header = "# Generated by vulnscan-ai. Review before running.\n"
    return header + json.dumps([play], indent=2) + "\n"
