# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 techhack
"""Export AI remediation plans as a ready-to-run bash script or Ansible playbook.

These are generated from the same `Remediation` objects the interactive `fix`
applies. The bash script reproduces the transactional safety net (backup +
validate-before-reload + rollback-on-failure); the Ansible playbook wraps the
commands with a backup step and a service handler. The playbook is emitted as
JSON (which is valid YAML) so we keep the project's stdlib-only footprint.
"""

from __future__ import annotations

import json
import os
import shlex
from typing import List

from .models import Finding


def _fix_findings(findings: List[Finding]) -> List[Finding]:
    return [f for f in findings if f.remediation
            and (f.remediation.commands or f.remediation.write_files)]


def _backup_set(rem) -> List[str]:
    """backup_paths plus any file the fix writes, de-duplicated (order kept)."""
    return list(dict.fromkeys(list(rem.backup_paths)
                              + [wf["path"] for wf in rem.write_files]))


def _bash_write_lines(wf: dict, indent: str) -> List[str]:
    """Render one write_files entry as a heredoc (works in a real shell)."""
    path, mode = wf["path"], wf.get("mode", "0644")
    lines: List[str] = []
    parent = os.path.dirname(path)
    if parent:
        lines.append(f"{indent}mkdir -p {shlex.quote(parent)}")
    # Heredoc body + terminator must sit at column 0, so they are not indented.
    lines.append(f"{indent}cat > {shlex.quote(path)} <<'VULNSCANAI_EOF'")
    lines.append(wf["content"].rstrip("\n"))
    lines.append("VULNSCANAI_EOF")
    lines.append(f"{indent}chmod {mode} {shlex.quote(path)}")
    return lines


def to_bash_script(findings: List[Finding]) -> str:
    """Render a self-contained, idempotent-ish bash remediation script."""
    out: List[str] = [
        "#!/usr/bin/env bash",
        "# Generated by vulnscan-ai. Review before running. Run as root.",
        "set -euo pipefail",
        "",
        'TS="$(date +%Y%m%d-%H%M%S)"',
        'BACKUP_ROOT="/var/backups/vulnscan-ai/$TS"',
        # A file the fix *creates* does not exist at backup time, so these must
        # never return non-zero (they run under `set -e` + an ERR trap).
        "backup() { for f in \"$@\"; do [ -f \"$f\" ] && install -D \"$f\" "
        "\"$BACKUP_ROOT$f\" || true; done; return 0; }",
        "restore() { for f in \"$@\"; do if [ -f \"$BACKUP_ROOT$f\" ]; then "
        "cp -a \"$BACKUP_ROOT$f\" \"$f\"; else rm -f \"$f\"; fi; done; return 0; }",
        "",
    ]
    for f in _fix_findings(findings):
        rem = f.remediation
        assert rem is not None
        out.append(f"# ===== {f.title} =====")
        if rem.summary:
            out.append(f"# {rem.summary}")
        out.append(f"# risk={rem.risk} confidence={rem.confidence:.0%}")
        transactional = bool(rem.backup_paths or rem.service or rem.validate_cmd
                             or rem.write_files)
        if transactional:
            backup_paths = _backup_set(rem)
            paths = " ".join(shlex.quote(p) for p in backup_paths)
            svc = rem.service or ""
            mode = rem.restart_mode if rem.restart_mode in ("reload", "restart") else ""
            reload_cmd = f"systemctl {mode} {svc}" if (svc and mode) else "true"
            out.append("(")
            out.append("  set -e")
            if paths:
                out.append(f"  backup {paths}")
            trap_restore = f"restore {paths}; " if paths else ""
            trap_reload = f"{reload_cmd} || true; " if (svc and mode) else ""
            out.append(f"  trap 'echo \"FAILED — rolling back\"; {trap_restore}"
                       f"{trap_reload}exit 1' ERR")
            for wf in rem.write_files:            # write files before commands
                out.extend(_bash_write_lines(wf, "  "))
            for c in rem.commands:
                out.append(f"  {c}")
            if rem.validate_cmd:
                out.append(f"  {rem.validate_cmd}   # validate before reload")
            if svc and mode:
                out.append(f"  {reload_cmd}")
            out.append(")")
        else:
            for c in rem.commands:
                out.append(c)
        out.append("")
    return "\n".join(out) + "\n"


def to_ansible_playbook(findings: List[Finding]) -> str:
    """Render an Ansible playbook (as JSON, which is valid YAML)."""
    tasks: List[dict] = []
    handlers: List[dict] = []
    seen_services = set()

    for f in _fix_findings(findings):
        rem = f.remediation
        assert rem is not None
        title = f.title or rem.summary or "remediation"
        notify = []
        if rem.service and rem.restart_mode in ("reload", "restart"):
            hname = f"{rem.restart_mode} {rem.service}"
            notify = [hname]
            if hname not in seen_services:
                seen_services.add(hname)
                handlers.append({
                    "name": hname,
                    "ansible.builtin.systemd": {
                        "name": rem.service, "state": f"{rem.restart_mode}ed",
                    },
                })
        for path in _backup_set(rem):
            tasks.append({
                "name": f"[{title}] backup {path}",
                "ansible.builtin.copy": {
                    "src": path, "dest": path, "remote_src": True, "backup": True,
                },
                "ignore_errors": True,     # the file may not exist yet (created below)
            })
        for wf in rem.write_files:
            copy = {"dest": wf["path"], "content": wf["content"],
                    "mode": wf.get("mode", "0644")}
            task = {"name": f"[{title}] write {wf['path']}",
                    "ansible.builtin.copy": copy}
            if notify:
                task["notify"] = notify
            tasks.append(task)
        for i, cmd in enumerate(rem.commands, 1):
            task = {
                "name": f"[{title}] step {i}",
                "ansible.builtin.shell": cmd,
            }
            if notify:
                task["notify"] = notify
            tasks.append(task)
        if rem.validate_cmd:
            tasks.append({
                "name": f"[{title}] validate config",
                "ansible.builtin.command": rem.validate_cmd,
                "changed_when": False,
            })

    play = {
        "name": "vulnscan-ai generated remediation",
        "hosts": "all",
        "become": True,
        "tasks": tasks,
        "handlers": handlers,
    }
    header = "# Generated by vulnscan-ai. Review before running.\n"
    return header + json.dumps([play], indent=2) + "\n"
